SELECT Ltrim(Rtrim(fecha))              AS date,
       Ltrim(Rtrim(codigo_fdo))         AS name, 
       Ltrim(Rtrim(codigo_ins))         AS instrument_code, 
       Ltrim(Rtrim(codigo_emi))         AS issuer_code, 
       monto 				AS market_value,
       porc 				AS pct_fund,
       cantidad 			AS nominal_amount,
       precio 				AS price,
       Ltrim(Rtrim(asset_clas))         AS asset_clas, 
       Ltrim(Rtrim(asset_clas_long))    AS asset_clas_Long, 
       Ltrim(Rtrim(riesgonativo))       AS native_risk, 
       Ltrim(Rtrim(c_l))                AS longshort, 
       Ltrim(Rtrim(subclase))           AS subclass, 
       Ltrim(Rtrim(moneda))             AS currency, 
       duration 			AS duration,
       tasa 				AS yield,
       tasabbdd 			AS yield_db,
       Ltrim(Rtrim(riesgo))             AS risk, 
       ordenriesgo 			AS risk_order,
       Ltrim(Rtrim(ar_br))              AS highlow_risk, 
       Ltrim(Rtrim(tipopapel))          AS bond_type, 
       Ltrim(Rtrim(riesg_dur_mon))      AS risk_dur_cur, 
       Ltrim(Rtrim(riesg_dur))          AS risk_dur, 
       Ltrim(Rtrim(dur_mon))            AS dur_cur, 
       Ltrim(Rtrim(tipopapel_dur))      AS instrument_type_dur,
       Ltrim(Rtrim(tipopapel_mon))      AS instrument_type_cur, 
       Ltrim(Rtrim(tipoinstr))          AS instrument_type,
       Ltrim(Rtrim(sector))             AS sector, 
       Ltrim(Rtrim(nombre_instrumento)) AS instrument_name,
       Ltrim(Rtrim(nombre_emisor))      AS issuer_name,
       Ltrim(Rtrim(fec_vcto))           AS maturity_date,
       nominal	 			AS nominal,
       Ltrim(Rtrim(portfolio_clas))     AS portfolio_clas, 
       porc * duration                  AS ctd
FROM   dbo.zhis_carteras 
WHERE  fecha = 'AUTODATE'